---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restservice
  namespace: java-apps
  labels:
    type: frontend
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      name: restservice
      labels:
        app: myapp
        salesRep: harsh
    spec:
      containers: 
      - name: restservice
        image: mhkadam/restapi:latest
      - name: appd-node-name
        valueFrom:
          fieldRef:
            fieldPath: metadata.name        

---
apiVersion: v1
kind: Service
metadata: 
  name: rest-api-service
  namespace: java-apps

spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 80
  selector:
    type: frontend
    app: myapp       
