apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp
    type: frontend
  name: restsvcaz
  namespace: demoapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30012
  selector:
    app: myapp
  type: LoadBalancer
status:
  loadBalancer: {}
